[INFO] [WallTime: 1437313250.357401] 'What can I do for you?'
[ERROR] [WallTime: 1437313262.051772] InvalidUserCodeError: Could not execute state 'HUMAN_ROBOT_INTERACTION' of type '<__main__.ConversationWithOperator object at 0x7f6b9f358810>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/indigo/system/src/challenge_open/src/challenge_open/challenge_open.py", line 288, in execute
    obj = res.choices['object']
KeyError: 'object'

[ERROR] [WallTime: 1437313262.052212] State 'HANDLE_GUI_CALL' failed to execute.
[ERROR] [WallTime: 1437313262.054276] Error: /home/amigo/ros/indigo/system/src/robot_smach_states/src/robot_smach_states/util/startup.py,69,startup,outcome = executioner.execute()
['/home/amigo/ros/indigo/system/src/robot_smach_states/src/robot_smach_states/util/startup.py', 69, 'startup', 'outcome = executioner.execute()', InvalidUserCodeError('Could not execute state \'HUMAN_ROBOT_INTERACTION\' of type \'<__main__.ConversationWithOperator object at 0x7f6b9f358810>\': Traceback (most recent call last):\n  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once\n    self._remappings[self._current_label]))\n  File "/home/amigo/ros/indigo/system/src/challenge_open/src/challenge_open/challenge_open.py", line 288, in execute\n    obj = res.choices[\'object\']\nKeyError: \'object\'\n',)]
