# Responsible: Loy

amigo1:

    amiddle-cleanup

amigo3:

    roslaunch challenge_cleanup clean_up_aux.launch

amigo3:

    rosrun challenge_cleanup clean_up.py


---------------------------------------


More info: 
- 2/3D navigation. Check robot_skills for that. Switch between 2/d will be made automagically later.
- roslaunch challenge_cleanup clean_up_aux.launch, which includes:
- 	#roslaunch run_speech_files speech_magdeburg2013.launch #should wait for it to finish launching
- 	#roslaunch speech_interpreter start.launch
- rosrun challenge_cleanup clean_up.py






---------------------------------------
BUGS: Remove bug if fixed:



[WARN] [WallTime: 1366912425.914622] not self.preempted = True
[WARN] [WallTime: 1366912425.915689] not SUCCEEDED = False
[INFO] [WallTime: 1366912425.925217] 'I have reached my goal'
[INFO] [WallTime: 1366912427.407344] 'I reached a meeting point'
[INFO] [WallTime: 1366912428.896667] State machine terminating 'ENTER_ROOM':'found':'Done'
[INFO] [WallTime: 1366912428.897044] State machine transitioning 'START_CHALLENGE':'Done'-->'ASK_CLEANUP'
[ERROR] [WallTime: 1366912428.908898] InvalidUserCodeError: Could not execute state 'ASK_CLEANUP' of type '<__main__.Ask_cleanup object at 0x7fdd740322d0>': Traceback (most recent call last):
  File "/opt/ros/fuerte/stacks/executive_smach/smach/src/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/fuerte/tue/trunk/tue_robocup/challenge_cleanup/src/clean_up.py", line 35, in execute
    self.response = self.get_cleanup_service("room_cleanup", 4 , 60)  # This means that within 4 tries and within 60 seconds an answer is received.
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 432, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    responses = transport.receive_once()
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 656, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 350, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 333, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
ServiceException: service [/interpreter/get_info_user] responded with an error: 

[ERROR] [WallTime: 1366912428.909990] Amigo exited with smach.exceptions.InvalidUserCodeError,<smach.exceptions.InvalidUserCodeError instance at 0x7fdd743fe0e0>,<traceback object at 0x7fdd7404d638>
[INFO] [WallTime: 1366912428.911758] Base cancelling goal on close
[INFO] [WallTime: 1366912428.912730] Spindle cancelling all goals on close
[INFO] [WallTime: 1366912428.914938] Arms cancelling all goals on all arm-related ACs on close
[INFO] [WallTime: 1366912428.919930] Arms cancelling all goals on all arm-related ACs on close
[INFO] [WallTime: 1366912428.922369] Arms cancelling all goals on all arm-related ACs on close
Traceback (most recent call last):
  File "/home/amigo/ros/fuerte/tue/trunk/tue_robocup/challenge_cleanup/src/clean_up.py", line 333, in <module>
    startup(Cleanup)
  File "/home/amigo/ros/fuerte/tue/trunk/tue_executioner/robot_smach_states/src/robot_smach_states/util/startup.py", line 56, in startup
    outcome = executioner.execute()
  File "/opt/ros/fuerte/stacks/executive_smach/smach/src/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/ros/fuerte/stacks/executive_smach/smach/src/smach/state_machine.py", line 246, in _update_once
    raise smach.InvalidUserCodeError("Could not execute state '%s' of type '%s': " % ( self._current_label, self._current_state ) + traceback.format_exc())
smach.exceptions.InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x7fdd743fe0e0>
